const users = [
    {
        id: '1',
        name: 'Irene Kovacs',
        position: 'Web Application Developer',
        phoneNo: '918-768-8029',
        email: 'ireneDKovacs@rhyta.com',
        salary: '$20,000 K',
        img: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg',
        facebook: 'https://www.facebook.com/tobibur96',
        linkedin: 'https://www.linkedin.com/in/tobibur',
        company: 'Hughes Markets'
    },
    {
        id: '2',
        name: 'Jeremy Souza',
        position: 'WordPress Developer',
        phoneNo: '413-279-7186',
        email: 'jeremyBSouza@dayrep.com',
        salary: '$30,000 K',
        img: 'https://images.pexels.com/photos/1516680/pexels-photo-1516680.jpeg',
        facebook: 'https://www.facebook.com/tobibur96',
        linkedin: 'https://www.linkedin.com/in/tobibur',
        company: 'Holly Tree Inn'
    },
    {
        id: '3',
        name: 'James Thompson',
        position: 'Java Developer',
        phoneNo: '334-257-8306',
        email: 'jamesVThompson@dayrep.com',
        salary: '$25,000 K',
        img: 'https://images.pexels.com/photos/3778602/pexels-photo-3778602.jpeg',
        facebook: 'https://www.facebook.com/tobibur96',
        linkedin: 'https://www.linkedin.com/in/tobibur',
        company: 'Hughes Markets'
    },
    {
        id: '4',
        name: 'Son McGuire',
        position: 'Web Developer',
        phoneNo: '918-768-8029',
        email: 'sonDMcGuire@teleworm.us',
        salary: '$20,000 K',
        img: 'https://images.pexels.com/photos/3777557/pexels-photo-3777557.jpeg',
        facebook: 'https://www.facebook.com/tobibur96',
        linkedin: 'https://www.linkedin.com/in/tobibur',
        company: 'Jafco'
    },
    {
        id: '5',
        name: 'Joe Emery',
        position: 'Web Application Developer',
        phoneNo: '281-967-8589',
        email: 'joeGEmery@jourrapide.com',
        salary: '$50,000 K',
        img: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg',
        facebook: 'https://www.facebook.com/tobibur96',
        linkedin: 'https://www.linkedin.com/in/tobibur',
        company: 'Penn Fruit'
    },
    {
        id: '6',
        name: 'Chase Winger',
        position: 'Web Developer',
        phoneNo: '601-233-8644',
        email: 'chaseRWinger@rhyta.com',
        salary: '$30,000 K',
        img: 'https://images.pexels.com/photos/3778198/pexels-photo-3778198.jpeg',
        facebook: 'https://www.facebook.com/tobibur96',
        linkedin: 'https://www.linkedin.com/in/tobibur',
        company: 'Holly Tree Inn'
    },
    {
        id: '7',
        name: 'James Eldredge',
        position: 'Web Application Developer',
        phoneNo: '425-493-0347',
        email: 'jamesEEldredge@dayrep.com',
        salary: '$20,000 K',
        img: 'https://images.pexels.com/photos/532220/pexels-photo-532220.jpeg',
        facebook: 'https://www.facebook.com/tobibur96',
        linkedin: 'https://www.linkedin.com/in/tobibur',
        company: 'Turtle Records'
    },
    {
        id: '8',
        name: 'Harold Milliken',
        position: 'Web Application Developer',
        phoneNo: '570-234-5385',
        email: 'haroldLMilliken@jourrapide.com',
        salary: '$45,000 K',
        img: 'https://images.pexels.com/photos/1043473/pexels-photo-1043473.jpeg',
        facebook: 'https://www.facebook.com/tobibur96',
        linkedin: 'https://www.linkedin.com/in/tobibur',
        company: 'MVP Sports'
    },
    {
        id: '9',
        name: 'Robert Waller',
        position: 'Web Application Developer',
        phoneNo: '843-483-6045',
        email: 'robertTWaller@jourrapide.com',
        salary: '$60,000 K',
        img: 'https://images.pexels.com/photos/775358/pexels-photo-775358.jpeg',
        facebook: 'https://www.facebook.com/tobibur96',
        linkedin: 'https://www.linkedin.com/in/tobibur',
        company: 'Sistemos'
    },
    
]